# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-GB"
title                    : "Eye Wellbeing"
title_separator          : "-"
name                     : &name "Friederike Wild"
tagline                  : "Improve your Eye Wellbeing"
description              : &description "About Friederike Wild - Coach for eye wellbeing based in London UK and online. Helping you to relax your eyes and improve your vision."
url                      : "https://eyewellbeing.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
gh_repo                  :
teaser                   : "teaser_default.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus"
  disqus:
    shortname            : "eyewellbeing"
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"

# SEO Related
google_site_verification : "vRuP0nse3n_Fu5Zb_5qT2BraiPYHT6LmCFHCkpcHxqg"
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter "eyewellbeing"
facebook:
  username               : &facebook "EyeWellbeing"
  app_id                 : 1803690799910199
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-86230620-1

# Google AdSense
google_ad_client         :
google_ad_slot           :

# Facebook Pixel
facebook_pixel_id        : 169000980299601


# Site Author
author:
  name             : *name
  avatar           : "bio-photo.jpg"
  bio              : "Coach for eye wellbeing and blogger promoting delicious vegan food."
  location         : "London UK"
  email            : &mail "coach@eyewellbeing.com"
  uri              : # http://veganised.co.uk
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : &facebook "EyeWellbeing"
  foursquare       :
  github           :
  google_plus      : "EyeWellbeing"
  keybase          :
  instagram        : &instagram "eyewellbeing"
  lastfm           :
  linkedin         : "friederike-wild-b933087"
  pinterest        : &pinterest "eyewellbeing"
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          : &twitter "eyewellbeing"
  vine             :
  weibo            :
  xing             :
  youtube          :


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false



# Collections
collections:
  treats:
    output: true
    permalink: /treats/:path/
    title: "Eye Treats"


# Defaults
defaults:
# _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
# _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
# _treats
  - scope:
      path: ""
      type: treats
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      comments: true



# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/London"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from
  - jekyll-auto-image

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-froms
  - jekyll-auto-image


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
categories:
  type: liquid
  path: /categories/
tags:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
